version: "3.8"

services:
  frontend:
    build: ./erp-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./erp-frontend:/app
    depends_on:
      - backend

  backend:
    build: ./erp-backend
    ports:
      - "4000:4000"
    volumes:
      - ./erp-backend:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
